### ISSUE TITLE
Replace SPARQL query

### ISSUE THREAD

**Issue by szeke** [research-software-company/wikidata-fuzzy-search#6]
SELECT ?variable ?variable_name ?country ?countryLabel ?time ?value WHERE {
  VALUES (?variable ?p ?ps) {
    (wd:P111319 p:P111319 ps:P111319)
  }
  VALUES (?country) {
    (wd:Q30) (wd:Q17)
  }
  ?country ?p ?o .
  ?o ?ps ?value .
  ?o pq:P585 ?time.
  
  ?variable skos:prefLabel ?variable_name.
  FILTER((LANG(?variable_name)) = "en")
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY ?country ?time

**Comment by zmbq** [comment]
OK, just to make sure we understand. P111319 is the property we're querying on (P1082 population, for instance). The qualifiers should be added as they are added today:

`OPTIONAL { ?o pq:P??? ?qualifierPropoperty . }`
And we add ?qualifierPropertyLabel to the SELECT list

**Comment by szeke** [comment]
Unfortunately it is more complex. We need to do 3 queries. One without qualifiers, second one to discover qualifier properties based on sample of results and third query to get all the results. 

I will send a longer explanation

P

**Comment by szeke** [comment]
It turns out we can do it with two queries. I put the explanation in Notion:
https://www.notion.so/szeke/Query-and-Filter-a6449600e81743a39ca3b8f021f74d9c <https://www.notion.so/szeke/Query-and-Filter-a6449600e81743a39ca3b8f021f74d9c>

Please check the notion when working on the tasks. In this task, for example, there is additional guidance for the columns of the table, which is not in the current implementation.

Were may need to tune the parameter K for sampling to get good efficiency. I set it to 25, which may be too large. 

P

Pedro Szekely
Principal Scientist / USC Information Sciences Institute
Research Director / Center on Knowledge Graphs, USC/ISI
Research Associate Professor / USC Viterbi Computer Science Department
pedro szekely <http://usc-isi-i2.github.io/szekely/> | kg center <http://usc-isi-i2.github.io/home/> | 562.889.3149

**Comment by zmbq** [comment]
I had to change the query a little bit, so I can get the qualifier the way the old query retrieved it. Here is the query I'm using:

```
                SELECT DISTINCT ?statement ?pq ?wdpqLabel ?qualifier_no_prefix WHERE {{
                    VALUES (?p) {{
                        (p:{self.pnode})
                    }}
                    VALUES ?country {{ { countries } }}
                    ?country ?p ?statement .
                    ?statement ?pq ?pqv .
                    ?wdpq wikibase:qualifier ?pq .
                    BIND(MD5(str(?statement)) as ?random)
                    BIND (STR(REPLACE(STR(?pq), STR(pq:), "")) AS ?qualifier_no_prefix)
                    SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en". }}
                }}
                ORDER BY ?random
                LIMIT 600
```

`self.pnode` is the property's code (P1082), and `countries` is the list of country codes ( `wd:Q30...`)

If you think this query is correct, I'll close this ticket.

**Comment by szeke** [comment]
The query looks fine. Closing.
