### ISSUE TITLE
Find the correct data-label-augmentation code

### ISSUE THREAD

**Issue by zmbq** [research-software-company/wikidata-fuzzy-search#9]
The code we have is incompatible with this repo.

**Comment by szeke** [comment]
@GreatYYX , we need your help to resolve this issue. We have a bluejeans meeting today Jan 14 at noon PT, please join.

**Comment by GreatYYX** [comment]
@zmbq you should have read permission of that repo. So you need to either clone this repo with all its submodules or manually clone `data-label-augmentation` and place it in this repo's clone and switch it to designated commit / branch which is `mint-fuzzy`. Also, I explained here https://github.com/usc-isi-i2/wikidata-fuzzy-search/blob/master/README.md that additional language model needs to be downloaded.

**Comment by GreatYYX** [comment]
![image](https://user-images.githubusercontent.com/8329846/72366823-e48f6180-36af-11ea-9707-ac59ca11fd4b.png)
^ `data-label-augmentation @ c253ab8` shows commit id
